project:
  type: website
  resources: 
    - 'papers/paper 8.0 final web.html'
    - 'papers/paper-8.0-final-web.pdf'
  output-dir: docs
  render:
    - "*.qmd"

website:
  google-analytics: G-CRVC0BS9GY

  navbar:
    tools:
      - icon: github
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - publications.qmd
      - projects.qmd
      - cv.qmd

format:
  html:
    theme: 
      light: journal
      dark: solar
    css: styles.css
    toc: false



