project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  google-analytics: G-CRVC0BS9GY
  # navbar:
  #   left:
  #     - href: cv.qmd

format:
  html:
    theme: 
      light: lumen
      dark: solar
    css: styles.css
    toc: true



