project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

format:
  html:
    email-obfuscation: javascript
    theme: 
      light: journal
      dark: solar
    toc: false
    from: markdown+emoji


website:
  google-analytics:
    tracking-id: "G-CRVC0BS9GY"
  navbar:
    tools:
      - icon: github
        href: https://github.com/YiquanGu
      - icon: linkedin
        href: https://www.linkedin.com/in/yiquan-gu-259067247/
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - publications.qmd
      - projects.qmd
      - cv.qmd




